// Comprehensive map of RBI-registered bank prefixes (4 uppercase letters) to official bank names
export const BANK_CODES = {
  // Public Sector Banks
  'SBIN': 'State Bank of India',
  'PUNB': 'Punjab National Bank',
  'BARB': 'Bank of Baroda',
  'CNRB': 'Canara Bank',
  'UBIN': 'Union Bank of India',
  'BKID': 'Bank of India',
  'IOBA': 'Indian Overseas Bank',
  'CBIN': 'Central Bank of India',
  'IDIB': 'Indian Bank',
  'MAHB': 'Bank of Maharashtra',
  'PSIB': 'Punjab & Sind Bank',
  'UCBA': 'UCO Bank',

  // Major Private Sector Banks
  'HDFC': 'HDFC Bank',
  'ICIC': 'ICICI Bank',
  'UTIB': 'Axis Bank',
  'KKBK': 'Kotak Mahindra Bank',
  'INDB': 'IndusInd Bank',
  'YESB': 'Yes Bank',
  'IDFB': 'IDFC First Bank',
  'FDRL': 'Federal Bank',
  'SIBL': 'South Indian Bank',
  'KARB': 'Karnataka Bank',
  'KVBL': 'Karur Vysya Bank',
  'TMBL': 'Tamilnad Mercantile Bank',
  'CSBK': 'CSB Bank',
  'RBLN': 'RBL Bank',
  'DCBL': 'DCB Bank',
  'BDBL': 'Bandhan Bank',
  'JAKA': 'Jammu & Kashmir Bank',
  'DLXB': 'Dhanlaxmi Bank',
  'NTBL': 'Nainital Bank',

  // Payments Banks
  'PYTM': 'Paytm Payments Bank',
  'AIRP': 'Airtel Payments Bank',
  'IPOS': 'India Post Payments Bank',
  'FINO': 'Fino Payments Bank',
  'JIOP': 'Jio Payments Bank',
  'NSDL': 'NSDL Payments Bank',

  // Small Finance Banks
  'AUBL': 'AU Small Finance Bank',
  'ESAF': 'ESAF Small Finance Bank',
  'EQTX': 'Equitas Small Finance Bank',
  'JSFB': 'Jana Small Finance Bank',
  'NESF': 'North East Small Finance Bank',
  'SRCB': 'Suryoday Small Finance Bank',
  'UCBA': 'Ujjivan Small Finance Bank',
  'UTKS': 'Utkarsh Small Finance Bank',
  'CLBL': 'Capital Small Finance Bank',
  'SMCB': 'Shivalik Small Finance Bank',
  'USFB': 'Unity Small Finance Bank',

  // Foreign Banks Operating in India
  'CITI': 'Citibank India',
  'SCBL': 'Standard Chartered Bank',
  'HSBC': 'HSBC India',
  'DEUT': 'Deutsche Bank',
  'BARC': 'Barclays Bank',
  'DBSS': 'DBS Bank India',
  'BNPA': 'BNP Paribas',
  'CHAS': 'JPMorgan Chase Bank',
  'BOFA': 'Bank of America',
  'ABNA': 'Royal Bank of Scotland',
  'MSNU': 'Morgan Stanley',
  'SOGE': 'Societe Generale',
  'MUCB': 'MUFG Bank',
  'SMBC': 'Sumitomo Mitsui Banking Corporation',

  // Prominent Co-operative and Regional Rural Banks
  'APBL': 'The Andhra Pradesh State Co-operative Bank',
  'MSCI': 'Maharashtra State Co-operative Bank',
  'COSB': 'Cosmos Co-operative Bank',
  'SVCB': 'SVC Co-operative Bank',
  'TJSB': 'TJSB Sahakari Bank',
  'GSCB': 'Gujarat State Co-operative Bank',
  'KSCB': 'Karnataka State Co-operative Apex Bank',
  'NKGS': 'NKGSB Co-operative Bank',
  'SBLS': 'Saraswat Co-operative Bank',
  'ABHY': 'Abhyudaya Co-operative Bank',
  'DNSB': 'Dombivli Nagari Sahakari Bank',
  'PMCB': 'Punjab & Maharashtra Co-operative Bank',
  'IBKL': 'IDBI Bank'
};
